image: jeanp413/python-test-workspace
tasks:
  - name: Init workspace
    init: |
      mkdir node_modules
      cp -r /home/gitpod/.cache/workspace/* ./node_modules
      yarn
      yarn compile
    command: |
      touch __init_task_done__
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
