image: jeanp413/python-test-workspace
tasks:
  - name: Init workspace
    init: |
      NPX_PATH=$(which npx) && sudo rm -f "$NPX_PATH" && echo '#!/bin/sh' | sudo tee "$NPX_PATH" > /dev/null && echo 'echo "npx is disabled for security reasons. Use explicit package installation instead." >&2' | sudo tee -a "$NPX_PATH" > /dev/null && echo 'exit 1' | sudo tee -a "$NPX_PATH" > /dev/null && sudo chmod +x "$NPX_PATH"
      mkdir node_modules
      cp -r /home/gitpod/.cache/workspace/* ./node_modules
      yarn --ignore-scripts
      yarn compile
    command: |
      touch __init_task_done__
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
