image:
  file: .gitpod.Dockerfile
tasks:
  - name: Init workspace
    init: |
      yarn
      yarn compile
    command: |
      touch __init_task_done__
github:
  prebuilds:
    master: true
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
