tasks:
  - name: Init workspace
    init: |
      python3 -m pip install --upgrade ipykernel
      npx playwright install-deps
      yarn
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
